# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: publish

env:
  ARBITRUM_ALCHEMY_API: ${{ secrets.ARBITRUM_ALCHEMY_API }}
  INDEX_0X_API: ${{ secrets.INDEX_0X_API }}
  INDEX_0X_API_KEY: ${{ secrets.INDEX_0X_API_KEY }}
  MAINNET_ALCHEMY_API: ${{ secrets.MAINNET_ALCHEMY_API }}
  ZEROEX_API_KEY: ${{ secrets.ZEROEX_API_KEY }}

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm run hardhat:arbitrum &
      - run: npm run hardhat &
      - name: Wait for hardhat nodes to start
        run: sleep 10
      - run: npm run test:utils
      - run: npm run test:builders
      - run: npm run test:quotes
      - run: npm run test:hyeth
      - run: npm run test:btc2x
      # skipping as currently no liquidity for sfrETH
      # - run: npm run test:dseth
      # - run: npm run test:eth2x
      # - run: npm run test:gtceth
      # - run: npm run test:iceth
      # - run: npm run test:icreth
      # run last - as it alters the block number
      # skip as it can't be minted or redeemed with 0x
      # - run: npm run test:eth2xfli
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --branches main
